
export const valueToName = (labels: Record<string, string | number>[], value: number): string | null => {
  return labels.find((label) => label.value === value)?.name ?? null;
};

export const valueToIndex = (labels: Record<string, string | number>[], value: number): number | null => {
  const index = labels.findIndex((label) => label.value === value);
  return index !== -1 ? index : null;
};

export const majorCommodityCrops: string[] = [
  "Flaxseed",
  "Wheat",
  "Barley",
  "Oats",
  "Canola",
  "Peas",
  "Corn",
  "Soy"
];

export const crops: string[] = [
  "Cereals",
  "Barley",
  "Other Grains",
  "Millet",
  "Oats",
  "Rye",
  "Spelt",
  "Triticale",
  "Wheat",
  "Switchgrass",
  "Sorghum",
  "Quinoa",
  "Winter Wheat",
  "Spring Wheat",
  "Corn",
  "Tobacco",
  "Ginseng",
  "Oilseeds",
  "Borage",
  "Camelina",
  "Canola and Rapeseed",
  "Flaxseed",
  "Mustard",
  "Safflower",
  "Sunflower",
  "Soybeans",
  "Pulses",
  "Other Pulses",
  "Peas",
  "Chickpeas",
  "Beans",
  "Fababeans",
  "Lentils",
  "Vegetables",
  "Tomatoes",
  "Potatoes",
  "Sugarbeets",
  "Other Vegetables",
  "Fruits",
  "Berries",
  "Blueberry",
  "Cranberry",
  "Other Berry",
  "Orchards",
  "Other Fruits",
  "Vineyards",
  "Hops",
  "Herbs",
  "Buckwheat",
  "Canaryseed",
  "Hemp",
  "Vetch",
  "Other Crops",
];

export const cropLabels = [
  { value: 0, color: "#000000", name: "Cloud" },
  { value: 10, color: "#000000", name: "Cloud" },
  { value: 20, color: "#3333ff", name: "Water" },
  { value: 30, color: "#996666", name: "Exposed Land and Barren" },
  { value: 34, color: "#cc6699", name: "Urban and Developed" },
  { value: 35, color: "#e1e1e1", name: "Greenhouses" },
  { value: 50, color: "#ffff00", name: "Shrubland" },
  { value: 80, color: "#993399", name: "Wetland" },
  { value: 85, color: "#501b50", name: "Peatland" },
  { value: 110, color: "#cccc00", name: "Grassland" },
  { value: 120, color: "#cc6600", name: "Agriculture (undifferentiated)" },
  { value: 122, color: "#ffcc33", name: "Pasture and Forages" },
  { value: 130, color: "#7899f6", name: "Too Wet to be Seeded" },
  { value: 131, color: "#ff9900", name: "Fallow" },
  { value: 132, color: "#660000", name: "Cereals" },
  { value: 133, color: "#dae31d", name: "Barley" },
  { value: 134, color: "#d6cc00", name: "Other Grains" },
  { value: 135, color: "#d2db25", name: "Millet" },
  { value: 136, color: "#d1d52b", name: "Oats" },
  { value: 137, color: "#cace32", name: "Rye" },
  { value: 138, color: "#c3c63a", name: "Spelt" },
  { value: 139, color: "#b9bc44", name: "Triticale" },
  { value: 140, color: "#a7b34d", name: "Wheat" },
  { value: 141, color: "#b9c64e", name: "Switchgrass" },
  { value: 142, color: "#999900", name: "Sorghum" },
  { value: 143, color: "#e9e2b1", name: "Quinoa" },
  { value: 145, color: "#92a55b", name: "Winter Wheat" },
  { value: 146, color: "#809769", name: "Spring Wheat" },
  { value: 147, color: "#ffff99", name: "Corn" },
  { value: 148, color: "#98887c", name: "Tobacco" },
  { value: 149, color: "#799b93", name: "Ginseng" },
  { value: 150, color: "#5ea263", name: "Oilseeds" },
  { value: 151, color: "#52ae77", name: "Borage" },
  { value: 152, color: "#41bf7a", name: "Camelina" },
  { value: 153, color: "#d6ff70", name: "Canola and Rapeseed" },
  { value: 154, color: "#8c8cff", name: "Flaxseed" },
  { value: 155, color: "#d6cc00", name: "Mustard" },
  { value: 156, color: "#ff7f00", name: "Safflower" },
  { value: 157, color: "#315491", name: "Sunflower" },
  { value: 158, color: "#cc9933", name: "Soybeans" },
  { value: 160, color: "#896e43", name: "Pulses" },
  { value: 161, color: "#996633", name: "Other Pulses" },
  { value: 162, color: "#8f6c3d", name: "Peas" },
  { value: 163, color: "#b6a472", name: "Chickpeas" },
  { value: 167, color: "#82654a", name: "Beans" },
  { value: 168, color: "#a39069", name: "Fababeans" },
  { value: 174, color: "#b85900", name: "Lentils" },
  { value: 175, color: "#b74b15", name: "Vegetables" },
  { value: 176, color: "#ff8a8a", name: "Tomatoes" },
  { value: 177, color: "#ffcccc", name: "Potatoes" },
  { value: 178, color: "#6f55ca", name: "Sugarbeets" },
  { value: 179, color: "#ffccff", name: "Other Vegetables" },
  { value: 180, color: "#dc5424", name: "Fruits" },
  { value: 181, color: "#d05a30", name: "Berries" },
  { value: 182, color: "#d20000", name: "Blueberry" },
  { value: 183, color: "#cc0000", name: "Cranberry" },
  { value: 185, color: "#dc3200", name: "Other Berry" },
  { value: 188, color: "#ff6666", name: "Orchards" },
  { value: 189, color: "#c5453b", name: "Other Fruits" },
  { value: 190, color: "#7442bd", name: "Vineyards" },
  { value: 191, color: "#ffcccc", name: "Hops" },
  { value: 192, color: "#b5fb05", name: "Sod" },
  { value: 193, color: "#ccff05", name: "Herbs" },
  { value: 194, color: "#07f98c", name: "Nursery" },
  { value: 195, color: "#00ffcc", name: "Buckwheat" },
  { value: 196, color: "#cc33cc", name: "Canaryseed" },
  { value: 197, color: "#8e7672", name: "Hemp" },
  { value: 198, color: "#b1954f", name: "Vetch" },
  { value: 199, color: "#749a66", name: "Other Crops" },
  { value: 200, color: "#009900", name: "Forest (undifferentiated)" },
  { value: 210, color: "#006600", name: "Coniferous" },
  { value: 220, color: "#00cc00", name: "Broadleaf" },
  { value: 230, color: "#cc9900", name: "Mixedwood" }
];

export const soilTextureLabels = [
  { value: 1, color: "#d5c36b", label: "Cl", name: "Clay" },
  { value: 2, color: "#b96947", label: "SiCl", name: "Silty Clay" },
  { value: 3, color: "#9d3706", label: "SaCl", name: "Sandy Clay" },
  { value: 4, color: "#ae868f", label: "ClLo", name: "Clay Loam" },
  { value: 5, color: "#f86714", label: "SiClLo", name: "Silty Clay Loam" },
  { value: 6, color: "#46d143", label: "SaClLo", name: "Sandy Clay Loam" },
  { value: 7, color: "#368f20", label: "Lo", name: "Loam" },
  { value: 8, color: "#3e5a14", label: "SiLo", name: "Silty Loam" },
  { value: 9, color: "#ffd557", label: "SaLo", name: "Sandy Loam" },
  { value: 10, color: "#fff72e", label: "Si", name: "Silt" },
  { value: 11, color: "#ff5a9d", label: "LoSa", name: "Loamy Sand" },
  { value: 12, color: "#ff005b", label: "Sa", name: "Sand" },
];

export const soilTaxonomyLabels = [
  { value: 0, color: "#ffffff", name: "NODATA" },
  { value: 1, color: "#adff2d", name: "Albaqualfs" },
  { value: 2, color: "#adff22", name: "Cryaqualfs" },
  { value: 4, color: "#a5ff2f", name: "Durixeralfs" },
  { value: 6, color: "#87ff37", name: "Endoaqualfs" },
  { value: 7, color: "#baf019", name: "Epiaqualfs" },
  { value: 9, color: "#87ff19", name: "Fragiaqualfs" },
  { value: 10, color: "#96f03d", name: "Fragiudalfs" },
  { value: 11, color: "#a3f52f", name: "Fragixeralfs" },
  { value: 12, color: "#aff319", name: "Fraglossudalfs" },
  { value: 13, color: "#91ff37", name: "Glossaqualfs" },
  { value: 14, color: "#9cf319", name: "Glossocryalfs" },
  { value: 15, color: "#9bff37", name: "Glossudalfs" },
  { value: 16, color: "#91ff19", name: "Haplocryalfs" },
  { value: 17, color: "#71ff37", name: "Haploxeralfs" },
  { value: 18, color: "#86ff19", name: "Hapludalfs" },
  { value: 19, color: "#a9d42d", name: "Haplustalfs" },
  { value: 25, color: "#aff519", name: "Natraqualfs" },
  { value: 26, color: "#9bff19", name: "Natrixeralfs" },
  { value: 27, color: "#9af024", name: "Natrudalfs" },
  { value: 28, color: "#a5fd2f", name: "Natrustalfs" },
  { value: 29, color: "#88ff37", name: "Palecryalfs" },
  { value: 30, color: "#afed19", name: "Paleudalfs" },
  { value: 31, color: "#71ff19", name: "Paleustalfs" },
  { value: 32, color: "#aff026", name: "Palexeralfs" },
  { value: 38, color: "#8cf537", name: "Rhodustalfs" },
  { value: 39, color: "#b7ff19", name: "Vermaqualfs" },
  { value: 41, color: "#7177c0", name: "Eutroboralfs" },
  { value: 42, color: "#9a85ec", name: "Ochraqualfs" },
  { value: 43, color: "#f5f5e1", name: "Glossoboralfs" },
  { value: 44, color: "#52cf5a", name: "Cryoboralfs" },
  { value: 45, color: "#e42777", name: "Natriboralfs" },
  { value: 46, color: "#4ef76d", name: "Paleboralfs" },
  { value: 50, color: "#ff00fb", name: "Cryaquands" },
  { value: 58, color: "#eb05eb", name: "Fulvicryands" },
  { value: 59, color: "#fa04fa", name: "Fulvudands" },
  { value: 61, color: "#fc04f5", name: "Haplocryands" },
  { value: 63, color: "#f50df0", name: "Haploxerands" },
  { value: 64, color: "#f118f1", name: "Hapludands" },
  { value: 74, color: "#fa0cfa", name: "Udivitrands" },
  { value: 75, color: "#fc05e1", name: "Ustivitrands" },
  { value: 76, color: "#f100d5", name: "Vitraquands" },
  { value: 77, color: "#eb09e6", name: "Vitricryands" },
  { value: 80, color: "#fa22fa", name: "Vitrixerands" },
  { value: 82, color: "#ffdab9", name: "Aquicambids" },
  { value: 83, color: "#f5d2bb", name: "Aquisalids" },
  { value: 85, color: "#e8c9b8", name: "Argidurids" },
  { value: 86, color: "#ffddc4", name: "Argigypsids" },
  { value: 87, color: "#e7cbc0", name: "Calciargids" },
  { value: 89, color: "#ffd2c3", name: "Calcigypsids" },
  { value: 90, color: "#f5d6bb", name: "Gypsiargids" },
  { value: 92, color: "#d5d3b9", name: "Haplargids" },
  { value: 93, color: "#e8d4b8", name: "Haplocalcids" },
  { value: 94, color: "#e7cdc0", name: "Haplocambids" },
  { value: 96, color: "#f3eac8", name: "Haplodurids" },
  { value: 97, color: "#a0c4ba", name: "Haplogypsids" },
  { value: 98, color: "#ffd2b9", name: "Haplosalids" },
  { value: 99, color: "#f5dabb", name: "Natrargids" },
  { value: 100, color: "#f5d5b9", name: "Natridurids" },
  { value: 101, color: "#e8ebb8", name: "Natrigypsids" },
  { value: 102, color: "#ffddc2", name: "Paleargids" },
  { value: 103, color: "#e7ffc0", name: "Petroargids" },
  { value: 104, color: "#f3e6c8", name: "Petrocalcids" },
  { value: 105, color: "#ffdab9", name: "Petrocambids" },
  { value: 107, color: "#f5cdb9", name: "Petrogypsids" },
  { value: 110, color: "#a91d30", name: "Calciorthids" },
  { value: 111, color: "#796578", name: "Camborthids" },
  { value: 112, color: "#d8ff6e", name: "Paleorthids" },
  { value: 113, color: "#177548", name: "Durorthids" },
  { value: 114, color: "#43efd6", name: "Durargids" },
  { value: 115, color: "#8496a9", name: "Gypsiorthids" },
  { value: 116, color: "#296819", name: "Nadurargids" },
  { value: 196, color: "#b22328", name: "Udifolists" },
  { value: 201, color: "#a2c7eb", name: "Borosaprists" },
  { value: 202, color: "#36ba79", name: "Medisaprists" },
  { value: 203, color: "#806797", name: "Borohemists" },
  { value: 206, color: "#cb5b5f", name: "Calcicryepts" },
  { value: 207, color: "#cd5c5c", name: "Calciustepts" },
  { value: 208, color: "#d94335", name: "Calcixerepts" },
  { value: 209, color: "#d35740", name: "Cryaquepts" },
  { value: 210, color: "#e05a5d", name: "Durixerepts" },
  { value: 212, color: "#cf5b5c", name: "Durustepts" },
  { value: 213, color: "#ca5964", name: "Dystrocryepts" },
  { value: 215, color: "#ca5d5f", name: "Dystroxerepts" },
  { value: 216, color: "#cd5e5a", name: "Dystrudepts" },
  { value: 217, color: "#ca5969", name: "Dystrustepts" },
  { value: 218, color: "#d95a35", name: "Endoaquepts" },
  { value: 219, color: "#d36240", name: "Epiaquepts" },
  { value: 220, color: "#e05c43", name: "Eutrudepts" },
  { value: 221, color: "#d64755", name: "Fragiaquepts" },
  { value: 222, color: "#cf595c", name: "Fragiudepts" },
  { value: 225, color: "#ff5f5f", name: "Halaquepts" },
  { value: 226, color: "#cd6058", name: "Haplocryepts" },
  { value: 228, color: "#d95f35", name: "Haploxerepts" },
  { value: 229, color: "#d35140", name: "Haplustepts" },
  { value: 230, color: "#d65a55", name: "Humaquepts" },
  { value: 231, color: "#e05c59", name: "Humicryepts" },
  { value: 233, color: "#cf525e", name: "Humixerepts" },
  { value: 234, color: "#c65978", name: "Humudepts" },
  { value: 235, color: "#f5615f", name: "Humustepts" },
  { value: 245, color: "#826f9a", name: "Ustochrepts" },
  { value: 246, color: "#cff41a", name: "Eutrochrepts" },
  { value: 247, color: "#4a6f31", name: "Dystrochrepts" },
  { value: 248, color: "#a96989", name: "Eutrocryepts" },
  { value: 249, color: "#e16438", name: "Haplaquepts" },
  { value: 250, color: "#24f640", name: "Xerochrepts" },
  { value: 251, color: "#88c1f9", name: "Cryochrepts" },
  { value: 252, color: "#f5d25c", name: "Fragiochrepts" },
  { value: 253, color: "#d74322", name: "Haplumbrepts" },
  { value: 254, color: "#7f939e", name: "Cryumbrepts" },
  { value: 255, color: "#41a545", name: "Dystropepts" },
  { value: 256, color: "#8f8340", name: "Vitrandepts" },
  { value: 268, color: "#09fe03", name: "Argialbolls" },
  { value: 269, color: "#0aff00", name: "Argiaquolls" },
  { value: 270, color: "#0ff30f", name: "Argicryolls" },
  { value: 271, color: "#02f00a", name: "Argiudolls" },
  { value: 272, color: "#0fc903", name: "Argiustolls" },
  { value: 273, color: "#17f000", name: "Argixerolls" },
  { value: 274, color: "#0cff00", name: "Calciaquolls" },
  { value: 275, color: "#0ac814", name: "Calcicryolls" },
  { value: 276, color: "#0cfe00", name: "Calciudolls" },
  { value: 277, color: "#0aff0a", name: "Calciustolls" },
  { value: 278, color: "#03ff05", name: "Calcixerolls" },
  { value: 279, color: "#1cf31c", name: "Cryaquolls" },
  { value: 280, color: "#24f000", name: "Cryrendolls" },
  { value: 283, color: "#00ff0c", name: "Durixerolls" },
  { value: 284, color: "#14c814", name: "Durustolls" },
  { value: 285, color: "#00fe4c", name: "Endoaquolls" },
  { value: 286, color: "#14ff96", name: "Epiaquolls" },
  { value: 287, color: "#44d205", name: "Haplocryolls" },
  { value: 289, color: "#05f305", name: "Haploxerolls" },
  { value: 290, color: "#62f00a", name: "Hapludolls" },
  { value: 291, color: "#0fcd03", name: "Haplustolls" },
  { value: 292, color: "#00d20f", name: "Haprendolls" },
  { value: 294, color: "#1add11", name: "Natraquolls" },
  { value: 296, color: "#09ff0c", name: "Natrixerolls" },
  { value: 297, color: "#03ff05", name: "Natrudolls" },
  { value: 298, color: "#05e700", name: "Natrustolls" },
  { value: 299, color: "#02f00a", name: "Palecryolls" },
  { value: 300, color: "#0fea03", name: "Paleudolls" },
  { value: 301, color: "#00f000", name: "Paleustolls" },
  { value: 302, color: "#0ccb0c", name: "Palexerolls" },
  { value: 303, color: "#14dd14", name: "Vermudolls" },
  { value: 306, color: "#6a685d", name: "Haploborolls" },
  { value: 307, color: "#fae6b9", name: "Argiborolls" },
  { value: 308, color: "#769a34", name: "Haplaquolls" },
  { value: 309, color: "#6ff2df", name: "Cryoborolls" },
  { value: 310, color: "#ca7fc6", name: "Natriborolls" },
  { value: 311, color: "#d8228f", name: "Calciborolls" },
  { value: 312, color: "#c01bf0", name: "Paleborolls" },
  { value: 342, color: "#d2bad3", name: "Alaquods" },
  { value: 343, color: "#d8c3cb", name: "Alorthods" },
  { value: 345, color: "#d4c6d4", name: "Duraquods" },
  { value: 348, color: "#d5bed5", name: "Durorthods" },
  { value: 349, color: "#ddb9dd", name: "Endoaquods" },
  { value: 350, color: "#d8d2d8", name: "Epiaquods" },
  { value: 351, color: "#d4c9d4", name: "Fragiaquods" },
  { value: 353, color: "#d2bad5", name: "Fragiorthods" },
  { value: 354, color: "#d5bad5", name: "Haplocryods" },
  { value: 356, color: "#d5b2d5", name: "Haplohumods" },
  { value: 357, color: "#d8c8d2", name: "Haplorthods" },
  { value: 358, color: "#d4cbd4", name: "Humicryods" },
  { value: 367, color: "#552638", name: "Haplaquods" },
  { value: 368, color: "#2571eb", name: "Cryorthods" },
  { value: 370, color: "#ffa514", name: "Albaquults" },
  { value: 371, color: "#f3a502", name: "Endoaquults" },
  { value: 372, color: "#fb7b00", name: "Epiaquults" },
  { value: 373, color: "#f0b405", name: "Fragiaquults" },
  { value: 374, color: "#f7a80f", name: "Fragiudults" },
  { value: 375, color: "#fb9113", name: "Haplohumults" },
  { value: 376, color: "#ffa519", name: "Haploxerults" },
  { value: 377, color: "#f3a702", name: "Hapludults" },
  { value: 378, color: "#fbba07", name: "Haplustults" },
  { value: 381, color: "#f7970f", name: "Kandiudults" },
  { value: 385, color: "#f3a702", name: "Kanhapludults" },
  { value: 387, color: "#fb5a00", name: "Paleaquults" },
  { value: 388, color: "#f0c005", name: "Palehumults" },
  { value: 389, color: "#f7810f", name: "Paleudults" },
  { value: 390, color: "#ff9c00", name: "Paleustults" },
  { value: 391, color: "#f3b002", name: "Palexerults" },
  { value: 396, color: "#f0b005", name: "Rhodudults" },
  { value: 399, color: "#f7980f", name: "Umbraquults" },
  { value: 401, color: "#4d7cfc", name: "Ochraquults" },
  { value: 403, color: "#ffff00", name: "Calciaquerts" },
  { value: 405, color: "#fafa05", name: "Calciusterts" },
  { value: 406, color: "#ebeb22", name: "Calcixererts" },
  { value: 409, color: "#ffff14", name: "Dystraquerts" },
  { value: 410, color: "#f1f10a", name: "Dystruderts" },
  { value: 412, color: "#fafa05", name: "Endoaquerts" },
  { value: 413, color: "#ebeb1e", name: "Epiaquerts" },
  { value: 414, color: "#f5eb0c", name: "Gypsitorrerts" },
  { value: 415, color: "#eef506", name: "Gypsiusterts" },
  { value: 417, color: "#f1f129", name: "Haplotorrerts" },
  { value: 418, color: "#fafa05", name: "Haploxererts" },
  { value: 419, color: "#ebeb0c", name: "Hapluderts" },
  { value: 420, color: "#f5d202", name: "Haplusterts" },
  { value: 422, color: "#ffd700", name: "Natraquerts" },
  { value: 424, color: "#f1f12b", name: "Salitorrerts" },
  { value: 429, color: "#a91fac", name: "Chromusterts" },
  { value: 430, color: "#2da468", name: "Pellusterts" },
  { value: 431, color: "#9a8b71", name: "Chromoxererts" },
  { value: 432, color: "#76b989", name: "Pelluderts" },
  { value: 433, color: "#713959", name: "Torrerts" }
]



